# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .component import *
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import khulnasoft_example.local as __local
    local = __local
else:
    local = _utilities.lazy_import('khulnasoft_example.local')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "example",
  "mod": "index",
  "fqn": "khulnasoft_example",
  "classes": {
   "example:index:Component": "Component"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "example",
  "token": "khulnasoft:providers:example",
  "fqn": "khulnasoft_example",
  "class": "Provider"
 }
]
"""
)
