# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import khulnasoft
import khulnasoft.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._inputs import *
import khulnasoft_random

__all__ = ['CatArgs', 'Cat']

@khulnasoft.input_type
class CatArgs:
    def __init__(__self__, *,
                 age: Optional[khulnasoft.Input[int]] = None,
                 pet: Optional[khulnasoft.Input['PetArgs']] = None):
        """
        The set of arguments for constructing a Cat resource.
        """
        if age is not None:
            khulnasoft.set(__self__, "age", age)
        if pet is not None:
            khulnasoft.set(__self__, "pet", pet)

    @property
    @khulnasoft.getter
    def age(self) -> Optional[khulnasoft.Input[int]]:
        return khulnasoft.get(self, "age")

    @age.setter
    def age(self, value: Optional[khulnasoft.Input[int]]):
        khulnasoft.set(self, "age", value)

    @property
    @khulnasoft.getter
    def pet(self) -> Optional[khulnasoft.Input['PetArgs']]:
        return khulnasoft.get(self, "pet")

    @pet.setter
    def pet(self, value: Optional[khulnasoft.Input['PetArgs']]):
        khulnasoft.set(self, "pet", value)


class Cat(khulnasoft.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[khulnasoft.ResourceOptions] = None,
                 age: Optional[khulnasoft.Input[int]] = None,
                 pet: Optional[khulnasoft.Input[Union['PetArgs', 'PetArgsDict']]] = None,
                 __props__=None):
        """
        Create a Cat resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param khulnasoft.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[CatArgs] = None,
                 opts: Optional[khulnasoft.ResourceOptions] = None):
        """
        Create a Cat resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param CatArgs args: The arguments to use to populate this resource's properties.
        :param khulnasoft.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CatArgs, khulnasoft.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[khulnasoft.ResourceOptions] = None,
                 age: Optional[khulnasoft.Input[int]] = None,
                 pet: Optional[khulnasoft.Input[Union['PetArgs', 'PetArgsDict']]] = None,
                 __props__=None):
        opts = khulnasoft.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, khulnasoft.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CatArgs.__new__(CatArgs)

            __props__.__dict__["age"] = age
            __props__.__dict__["pet"] = pet
            __props__.__dict__["name"] = None
        super(Cat, __self__).__init__(
            'example::Cat',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: khulnasoft.Input[str],
            opts: Optional[khulnasoft.ResourceOptions] = None) -> 'Cat':
        """
        Get an existing Cat resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param khulnasoft.Input[str] id: The unique provider ID of the resource to lookup.
        :param khulnasoft.ResourceOptions opts: Options for the resource.
        """
        opts = khulnasoft.ResourceOptions.merge(opts, khulnasoft.ResourceOptions(id=id))

        __props__ = CatArgs.__new__(CatArgs)

        __props__.__dict__["name"] = None
        return Cat(resource_name, opts=opts, __props__=__props__)

    @property
    @khulnasoft.getter
    def name(self) -> khulnasoft.Output[Optional[str]]:
        return khulnasoft.get(self, "name")

