[build.environment]
  DISABLE_ESLINT_PLUGIN="true"

[build]
  # default build command
  command = "cd apps/web && pnpm run envsetup && cd ../../ && pnpm run build:web --skip-nx-cache"

[context.deploy-preview]
  command = "cd apps/web && pnpm run envsetup && cd ../../ && pnpm run build:web --skip-nx-cache"

[[redirects]]
  from = "https://dev.web.khulnasoft.co/*"
  to = "https://dashboard.khulnasoft-staging.co/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://dev.web.khulnasoft.co/*"
  to = "http://dashboard.khulnasoft-staging.co/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://dev.dashboard.khulnasoft.co/*"
  to = "https://dashboard.khulnasoft-staging.co/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://dev.dashboard.khulnasoft.co/*"
  to = "http://dashboard.khulnasoft-staging.co/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://web.khulnasoft.co/*"
  to = "https://dashboard.khulnasoft.co/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://web.khulnasoft.co/*"
  to = "http://dashboard.khulnasoft.co/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://eu.web.khulnasoft.co/*"
  to = "https://eu.dashboard.khulnasoft.co/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://eu.web.khulnasoft.co/*"
  to = "http://eu.dashboard.khulnasoft.co/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/auth/application"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "credentialless"
    Cross-Origin-Resource-Policy = "cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''

[[headers]]
  for = "/playground"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "credentialless"
    Cross-Origin-Resource-Policy = "cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''

[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''
