# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import khulnasoft
import khulnasoft.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'FooArgs',
    'FooArgsDict',
]

MYPY = False

if not MYPY:
    class FooArgsDict(TypedDict):
        a: NotRequired[khulnasoft.Input[bool]]
elif False:
    FooArgsDict: TypeAlias = Mapping[str, Any]

@khulnasoft.input_type
class FooArgs:
    def __init__(__self__, *,
                 a: Optional[khulnasoft.Input[bool]] = None):
        if a is not None:
            khulnasoft.set(__self__, "a", a)

    @property
    @khulnasoft.getter
    def a(self) -> Optional[khulnasoft.Input[bool]]:
        return khulnasoft.get(self, "a")

    @a.setter
    def a(self, value: Optional[khulnasoft.Input[bool]]):
        khulnasoft.set(self, "a", value)


