image:
  file: .gitpod/Dockerfile

# See: https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: >
      mkdir -p /workspace/opt-khulnasoft &&
      sudo ln -s /workspace/opt-khulnasoft $HOME/.khulnasoft-dev
    init: >
      make ensure &&
      make install
    command: khulnasoft version

# See: https://www.gitpod.io/docs/prebuilds/#configure-the-github-app
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
