# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import khulnasoft
import khulnasoft.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'FuncWithAllOptionalInputsResult',
    'AwaitableFuncWithAllOptionalInputsResult',
    'func_with_all_optional_inputs',
    'func_with_all_optional_inputs_output',
]

@khulnasoft.output_type
class FuncWithAllOptionalInputsResult:
    def __init__(__self__, r=None):
        if r and not isinstance(r, str):
            raise TypeError("Expected argument 'r' to be a str")
        khulnasoft.set(__self__, "r", r)

    @property
    @khulnasoft.getter
    def r(self) -> str:
        return khulnasoft.get(self, "r")


class AwaitableFuncWithAllOptionalInputsResult(FuncWithAllOptionalInputsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return FuncWithAllOptionalInputsResult(
            r=self.r)


def func_with_all_optional_inputs(a: Optional[str] = None,
                                  b: Optional[str] = None,
                                  opts: Optional[khulnasoft.InvokeOptions] = None) -> AwaitableFuncWithAllOptionalInputsResult:
    """
    Check codegen of functions with all optional inputs.


    :param str a: Property A
    :param str b: Property B
    """
    __args__ = dict()
    __args__['a'] = a
    __args__['b'] = b
    opts = khulnasoft.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = khulnasoft.runtime.invoke('configstation::funcWithAllOptionalInputs', __args__, opts=opts, typ=FuncWithAllOptionalInputsResult).value

    return AwaitableFuncWithAllOptionalInputsResult(
        r=khulnasoft.get(__ret__, 'r'))
def func_with_all_optional_inputs_output(a: Optional[khulnasoft.Input[Optional[str]]] = None,
                                         b: Optional[khulnasoft.Input[Optional[str]]] = None,
                                         opts: Optional[khulnasoft.InvokeOptions] = None) -> khulnasoft.Output[FuncWithAllOptionalInputsResult]:
    """
    Check codegen of functions with all optional inputs.


    :param str a: Property A
    :param str b: Property B
    """
    __args__ = dict()
    __args__['a'] = a
    __args__['b'] = b
    opts = khulnasoft.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = khulnasoft.runtime.invoke_output('configstation::funcWithAllOptionalInputs', __args__, opts=opts, typ=FuncWithAllOptionalInputsResult)
    return __ret__.apply(lambda __response__: FuncWithAllOptionalInputsResult(
        r=khulnasoft.get(__response__, 'r')))
