# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import khulnasoft
import khulnasoft.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'Sandwich',
]

@khulnasoft.output_type
class Sandwich(dict):
    def __init__(__self__, *,
                 bread: Optional[str] = None,
                 veggies: Optional[Sequence[str]] = None):
        if bread is not None:
            khulnasoft.set(__self__, "bread", bread)
        if veggies is not None:
            khulnasoft.set(__self__, "veggies", veggies)

    @property
    @khulnasoft.getter
    def bread(self) -> Optional[str]:
        return khulnasoft.get(self, "bread")

    @property
    @khulnasoft.getter
    def veggies(self) -> Optional[Sequence[str]]:
        return khulnasoft.get(self, "veggies")


