# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import khulnasoft
import khulnasoft.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'BastionShareableLink',
    'BastionShareableLinkDict',
]

MYPY = False

if not MYPY:
    class BastionShareableLinkDict(TypedDict):
        """
        Bastion Shareable Link.
        """
        vm: str
        """
        Reference of the virtual machine resource.
        """
elif False:
    BastionShareableLinkDict: TypeAlias = Mapping[str, Any]

@khulnasoft.input_type
class BastionShareableLink:
    def __init__(__self__, *,
                 vm: str):
        """
        Bastion Shareable Link.
        :param str vm: Reference of the virtual machine resource.
        """
        khulnasoft.set(__self__, "vm", vm)

    @property
    @khulnasoft.getter
    def vm(self) -> str:
        """
        Reference of the virtual machine resource.
        """
        return khulnasoft.get(self, "vm")

    @vm.setter
    def vm(self, value: str):
        khulnasoft.set(self, "vm", value)


