# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import khulnasoft
import khulnasoft.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'FuncWithDictParamResult',
    'AwaitableFuncWithDictParamResult',
    'func_with_dict_param',
    'func_with_dict_param_output',
]

@khulnasoft.output_type
class FuncWithDictParamResult:
    def __init__(__self__, r=None):
        if r and not isinstance(r, str):
            raise TypeError("Expected argument 'r' to be a str")
        khulnasoft.set(__self__, "r", r)

    @property
    @khulnasoft.getter
    def r(self) -> str:
        return khulnasoft.get(self, "r")


class AwaitableFuncWithDictParamResult(FuncWithDictParamResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return FuncWithDictParamResult(
            r=self.r)


def func_with_dict_param(a: Optional[Mapping[str, str]] = None,
                         b: Optional[str] = None,
                         opts: Optional[khulnasoft.InvokeOptions] = None) -> AwaitableFuncWithDictParamResult:
    """
    Check codegen of functions with a Dict<str,str> parameter.
    """
    __args__ = dict()
    __args__['a'] = a
    __args__['b'] = b
    opts = khulnasoft.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = khulnasoft.runtime.invoke('mypkg::funcWithDictParam', __args__, opts=opts, typ=FuncWithDictParamResult).value

    return AwaitableFuncWithDictParamResult(
        r=khulnasoft.get(__ret__, 'r'))
def func_with_dict_param_output(a: Optional[khulnasoft.Input[Optional[Mapping[str, str]]]] = None,
                                b: Optional[khulnasoft.Input[Optional[str]]] = None,
                                opts: Optional[khulnasoft.InvokeOptions] = None) -> khulnasoft.Output[FuncWithDictParamResult]:
    """
    Check codegen of functions with a Dict<str,str> parameter.
    """
    __args__ = dict()
    __args__['a'] = a
    __args__['b'] = b
    opts = khulnasoft.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = khulnasoft.runtime.invoke_output('mypkg::funcWithDictParam', __args__, opts=opts, typ=FuncWithDictParamResult)
    return __ret__.apply(lambda __response__: FuncWithDictParamResult(
        r=khulnasoft.get(__response__, 'r')))
