// *** WARNING: this file was generated by test. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as khulnasoft from "@khulnasoft/khulnasoft";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ServerPropertiesForReplicaArgs {
    createMode: khulnasoft.Input<"Replica">;
    version?: khulnasoft.Input<string>;
}

export interface ServerPropertiesForRestoreArgs {
    createMode: khulnasoft.Input<"PointInTimeRestore">;
    restorePointInTime: khulnasoft.Input<string>;
}
