// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package example

import (
	"context"
	"reflect"

	"errors"
	"github.com/khulnasoft/khulnasoft/sdk/v3/go/khulnasoft"
	"github.com/khulnasoft/khulnasoft/sdk/v3/go/khulnasoftx"
	"simple-resource-with-aliases/example/internal"
)

type BasicResourceV3 struct {
	khulnasoft.CustomResourceState

	Bar khulnasoftx.Output[string] `khulnasoft:"bar"`
}

// NewBasicResourceV3 registers a new resource with the given unique name, arguments, and options.
func NewBasicResourceV3(ctx *khulnasoft.Context,
	name string, args *BasicResourceV3Args, opts ...khulnasoft.ResourceOption) (*BasicResourceV3, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Bar == nil {
		return nil, errors.New("invalid value for required argument 'Bar'")
	}
	aliases := khulnasoft.Aliases([]khulnasoft.Alias{
		{
			Type: khulnasoft.String("example:index:BasicResource"),
		},
		{
			Type: khulnasoft.String("example:index:BasicResourceV2"),
		},
	})
	opts = append(opts, aliases)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource BasicResourceV3
	err := ctx.RegisterResource("example:index:BasicResourceV3", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBasicResourceV3 gets an existing BasicResourceV3 resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBasicResourceV3(ctx *khulnasoft.Context,
	name string, id khulnasoft.IDInput, state *BasicResourceV3State, opts ...khulnasoft.ResourceOption) (*BasicResourceV3, error) {
	var resource BasicResourceV3
	err := ctx.ReadResource("example:index:BasicResourceV3", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering BasicResourceV3 resources.
type basicResourceV3State struct {
}

type BasicResourceV3State struct {
}

func (BasicResourceV3State) ElementType() reflect.Type {
	return reflect.TypeOf((*basicResourceV3State)(nil)).Elem()
}

type basicResourceV3Args struct {
	Bar string `khulnasoft:"bar"`
}

// The set of arguments for constructing a BasicResourceV3 resource.
type BasicResourceV3Args struct {
	Bar khulnasoftx.Input[string]
}

func (BasicResourceV3Args) ElementType() reflect.Type {
	return reflect.TypeOf((*basicResourceV3Args)(nil)).Elem()
}

type BasicResourceV3Output struct{ *khulnasoft.OutputState }

func (BasicResourceV3Output) ElementType() reflect.Type {
	return reflect.TypeOf((*BasicResourceV3)(nil)).Elem()
}

func (o BasicResourceV3Output) ToBasicResourceV3Output() BasicResourceV3Output {
	return o
}

func (o BasicResourceV3Output) ToBasicResourceV3OutputWithContext(ctx context.Context) BasicResourceV3Output {
	return o
}

func (o BasicResourceV3Output) ToOutput(ctx context.Context) khulnasoftx.Output[BasicResourceV3] {
	return khulnasoftx.Output[BasicResourceV3]{
		OutputState: o.OutputState,
	}
}

func (o BasicResourceV3Output) Bar() khulnasoftx.Output[string] {
	value := khulnasoftx.Apply[BasicResourceV3](o, func(v BasicResourceV3) khulnasoftx.Output[string] { return v.Bar })
	return khulnasoftx.Flatten[string, khulnasoftx.Output[string]](value)
}

func init() {
	khulnasoft.RegisterOutputType(BasicResourceV3Output{})
}
