// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mypkg

import (
	"context"
	"reflect"

	"github.com/khulnasoft/khulnasoft/sdk/v3/go/khulnasoft"
	"github.com/khulnasoft/khulnasoft/sdk/v3/go/khulnasoftx"
	"output-funcs/mypkg/internal"
)

var _ = internal.GetEnvOrDefault

// Bastion Shareable Link.
type BastionShareableLink struct {
	// Reference of the virtual machine resource.
	Vm string `khulnasoft:"vm"`
}

// BastionShareableLinkInput is an input type that accepts BastionShareableLinkArgs and BastionShareableLinkOutput values.
// You can construct a concrete instance of `BastionShareableLinkInput` via:
//
//	BastionShareableLinkArgs{...}
type BastionShareableLinkInput interface {
	khulnasoft.Input

	ToBastionShareableLinkOutput() BastionShareableLinkOutput
	ToBastionShareableLinkOutputWithContext(context.Context) BastionShareableLinkOutput
}

// Bastion Shareable Link.
type BastionShareableLinkArgs struct {
	// Reference of the virtual machine resource.
	Vm khulnasoft.StringInput `khulnasoft:"vm"`
}

func (BastionShareableLinkArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*BastionShareableLink)(nil)).Elem()
}

func (i BastionShareableLinkArgs) ToBastionShareableLinkOutput() BastionShareableLinkOutput {
	return i.ToBastionShareableLinkOutputWithContext(context.Background())
}

func (i BastionShareableLinkArgs) ToBastionShareableLinkOutputWithContext(ctx context.Context) BastionShareableLinkOutput {
	return khulnasoft.ToOutputWithContext(ctx, i).(BastionShareableLinkOutput)
}

func (i BastionShareableLinkArgs) ToOutput(ctx context.Context) khulnasoftx.Output[BastionShareableLink] {
	return khulnasoftx.Output[BastionShareableLink]{
		OutputState: i.ToBastionShareableLinkOutputWithContext(ctx).OutputState,
	}
}

// BastionShareableLinkArrayInput is an input type that accepts BastionShareableLinkArray and BastionShareableLinkArrayOutput values.
// You can construct a concrete instance of `BastionShareableLinkArrayInput` via:
//
//	BastionShareableLinkArray{ BastionShareableLinkArgs{...} }
type BastionShareableLinkArrayInput interface {
	khulnasoft.Input

	ToBastionShareableLinkArrayOutput() BastionShareableLinkArrayOutput
	ToBastionShareableLinkArrayOutputWithContext(context.Context) BastionShareableLinkArrayOutput
}

type BastionShareableLinkArray []BastionShareableLinkInput

func (BastionShareableLinkArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]BastionShareableLink)(nil)).Elem()
}

func (i BastionShareableLinkArray) ToBastionShareableLinkArrayOutput() BastionShareableLinkArrayOutput {
	return i.ToBastionShareableLinkArrayOutputWithContext(context.Background())
}

func (i BastionShareableLinkArray) ToBastionShareableLinkArrayOutputWithContext(ctx context.Context) BastionShareableLinkArrayOutput {
	return khulnasoft.ToOutputWithContext(ctx, i).(BastionShareableLinkArrayOutput)
}

func (i BastionShareableLinkArray) ToOutput(ctx context.Context) khulnasoftx.Output[[]BastionShareableLink] {
	return khulnasoftx.Output[[]BastionShareableLink]{
		OutputState: i.ToBastionShareableLinkArrayOutputWithContext(ctx).OutputState,
	}
}

// Bastion Shareable Link.
type BastionShareableLinkOutput struct{ *khulnasoft.OutputState }

func (BastionShareableLinkOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*BastionShareableLink)(nil)).Elem()
}

func (o BastionShareableLinkOutput) ToBastionShareableLinkOutput() BastionShareableLinkOutput {
	return o
}

func (o BastionShareableLinkOutput) ToBastionShareableLinkOutputWithContext(ctx context.Context) BastionShareableLinkOutput {
	return o
}

func (o BastionShareableLinkOutput) ToOutput(ctx context.Context) khulnasoftx.Output[BastionShareableLink] {
	return khulnasoftx.Output[BastionShareableLink]{
		OutputState: o.OutputState,
	}
}

// Reference of the virtual machine resource.
func (o BastionShareableLinkOutput) Vm() khulnasoft.StringOutput {
	return o.ApplyT(func(v BastionShareableLink) string { return v.Vm }).(khulnasoft.StringOutput)
}

type BastionShareableLinkArrayOutput struct{ *khulnasoft.OutputState }

func (BastionShareableLinkArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]BastionShareableLink)(nil)).Elem()
}

func (o BastionShareableLinkArrayOutput) ToBastionShareableLinkArrayOutput() BastionShareableLinkArrayOutput {
	return o
}

func (o BastionShareableLinkArrayOutput) ToBastionShareableLinkArrayOutputWithContext(ctx context.Context) BastionShareableLinkArrayOutput {
	return o
}

func (o BastionShareableLinkArrayOutput) ToOutput(ctx context.Context) khulnasoftx.Output[[]BastionShareableLink] {
	return khulnasoftx.Output[[]BastionShareableLink]{
		OutputState: o.OutputState,
	}
}

func (o BastionShareableLinkArrayOutput) Index(i khulnasoft.IntInput) BastionShareableLinkOutput {
	return khulnasoft.All(o, i).ApplyT(func(vs []interface{}) BastionShareableLink {
		return vs[0].([]BastionShareableLink)[vs[1].(int)]
	}).(BastionShareableLinkOutput)
}

// Ssis environment reference.
type SsisEnvironmentReferenceResponse struct {
	// Environment folder name.
	EnvironmentFolderName *string `khulnasoft:"environmentFolderName"`
	// Environment name.
	EnvironmentName *string `khulnasoft:"environmentName"`
	// Environment reference id.
	Id *float64 `khulnasoft:"id"`
	// Reference type
	ReferenceType *string `khulnasoft:"referenceType"`
}

// SsisEnvironmentReferenceResponseInput is an input type that accepts SsisEnvironmentReferenceResponseArgs and SsisEnvironmentReferenceResponseOutput values.
// You can construct a concrete instance of `SsisEnvironmentReferenceResponseInput` via:
//
//	SsisEnvironmentReferenceResponseArgs{...}
type SsisEnvironmentReferenceResponseInput interface {
	khulnasoft.Input

	ToSsisEnvironmentReferenceResponseOutput() SsisEnvironmentReferenceResponseOutput
	ToSsisEnvironmentReferenceResponseOutputWithContext(context.Context) SsisEnvironmentReferenceResponseOutput
}

// Ssis environment reference.
type SsisEnvironmentReferenceResponseArgs struct {
	// Environment folder name.
	EnvironmentFolderName khulnasoft.StringPtrInput `khulnasoft:"environmentFolderName"`
	// Environment name.
	EnvironmentName khulnasoft.StringPtrInput `khulnasoft:"environmentName"`
	// Environment reference id.
	Id khulnasoft.Float64PtrInput `khulnasoft:"id"`
	// Reference type
	ReferenceType khulnasoft.StringPtrInput `khulnasoft:"referenceType"`
}

func (SsisEnvironmentReferenceResponseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SsisEnvironmentReferenceResponse)(nil)).Elem()
}

func (i SsisEnvironmentReferenceResponseArgs) ToSsisEnvironmentReferenceResponseOutput() SsisEnvironmentReferenceResponseOutput {
	return i.ToSsisEnvironmentReferenceResponseOutputWithContext(context.Background())
}

func (i SsisEnvironmentReferenceResponseArgs) ToSsisEnvironmentReferenceResponseOutputWithContext(ctx context.Context) SsisEnvironmentReferenceResponseOutput {
	return khulnasoft.ToOutputWithContext(ctx, i).(SsisEnvironmentReferenceResponseOutput)
}

func (i SsisEnvironmentReferenceResponseArgs) ToOutput(ctx context.Context) khulnasoftx.Output[SsisEnvironmentReferenceResponse] {
	return khulnasoftx.Output[SsisEnvironmentReferenceResponse]{
		OutputState: i.ToSsisEnvironmentReferenceResponseOutputWithContext(ctx).OutputState,
	}
}

// SsisEnvironmentReferenceResponseArrayInput is an input type that accepts SsisEnvironmentReferenceResponseArray and SsisEnvironmentReferenceResponseArrayOutput values.
// You can construct a concrete instance of `SsisEnvironmentReferenceResponseArrayInput` via:
//
//	SsisEnvironmentReferenceResponseArray{ SsisEnvironmentReferenceResponseArgs{...} }
type SsisEnvironmentReferenceResponseArrayInput interface {
	khulnasoft.Input

	ToSsisEnvironmentReferenceResponseArrayOutput() SsisEnvironmentReferenceResponseArrayOutput
	ToSsisEnvironmentReferenceResponseArrayOutputWithContext(context.Context) SsisEnvironmentReferenceResponseArrayOutput
}

type SsisEnvironmentReferenceResponseArray []SsisEnvironmentReferenceResponseInput

func (SsisEnvironmentReferenceResponseArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SsisEnvironmentReferenceResponse)(nil)).Elem()
}

func (i SsisEnvironmentReferenceResponseArray) ToSsisEnvironmentReferenceResponseArrayOutput() SsisEnvironmentReferenceResponseArrayOutput {
	return i.ToSsisEnvironmentReferenceResponseArrayOutputWithContext(context.Background())
}

func (i SsisEnvironmentReferenceResponseArray) ToSsisEnvironmentReferenceResponseArrayOutputWithContext(ctx context.Context) SsisEnvironmentReferenceResponseArrayOutput {
	return khulnasoft.ToOutputWithContext(ctx, i).(SsisEnvironmentReferenceResponseArrayOutput)
}

func (i SsisEnvironmentReferenceResponseArray) ToOutput(ctx context.Context) khulnasoftx.Output[[]SsisEnvironmentReferenceResponse] {
	return khulnasoftx.Output[[]SsisEnvironmentReferenceResponse]{
		OutputState: i.ToSsisEnvironmentReferenceResponseArrayOutputWithContext(ctx).OutputState,
	}
}

// Ssis environment reference.
type SsisEnvironmentReferenceResponseOutput struct{ *khulnasoft.OutputState }

func (SsisEnvironmentReferenceResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SsisEnvironmentReferenceResponse)(nil)).Elem()
}

func (o SsisEnvironmentReferenceResponseOutput) ToSsisEnvironmentReferenceResponseOutput() SsisEnvironmentReferenceResponseOutput {
	return o
}

func (o SsisEnvironmentReferenceResponseOutput) ToSsisEnvironmentReferenceResponseOutputWithContext(ctx context.Context) SsisEnvironmentReferenceResponseOutput {
	return o
}

func (o SsisEnvironmentReferenceResponseOutput) ToOutput(ctx context.Context) khulnasoftx.Output[SsisEnvironmentReferenceResponse] {
	return khulnasoftx.Output[SsisEnvironmentReferenceResponse]{
		OutputState: o.OutputState,
	}
}

// Environment folder name.
func (o SsisEnvironmentReferenceResponseOutput) EnvironmentFolderName() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisEnvironmentReferenceResponse) *string { return v.EnvironmentFolderName }).(khulnasoft.StringPtrOutput)
}

// Environment name.
func (o SsisEnvironmentReferenceResponseOutput) EnvironmentName() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisEnvironmentReferenceResponse) *string { return v.EnvironmentName }).(khulnasoft.StringPtrOutput)
}

// Environment reference id.
func (o SsisEnvironmentReferenceResponseOutput) Id() khulnasoft.Float64PtrOutput {
	return o.ApplyT(func(v SsisEnvironmentReferenceResponse) *float64 { return v.Id }).(khulnasoft.Float64PtrOutput)
}

// Reference type
func (o SsisEnvironmentReferenceResponseOutput) ReferenceType() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisEnvironmentReferenceResponse) *string { return v.ReferenceType }).(khulnasoft.StringPtrOutput)
}

type SsisEnvironmentReferenceResponseArrayOutput struct{ *khulnasoft.OutputState }

func (SsisEnvironmentReferenceResponseArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SsisEnvironmentReferenceResponse)(nil)).Elem()
}

func (o SsisEnvironmentReferenceResponseArrayOutput) ToSsisEnvironmentReferenceResponseArrayOutput() SsisEnvironmentReferenceResponseArrayOutput {
	return o
}

func (o SsisEnvironmentReferenceResponseArrayOutput) ToSsisEnvironmentReferenceResponseArrayOutputWithContext(ctx context.Context) SsisEnvironmentReferenceResponseArrayOutput {
	return o
}

func (o SsisEnvironmentReferenceResponseArrayOutput) ToOutput(ctx context.Context) khulnasoftx.Output[[]SsisEnvironmentReferenceResponse] {
	return khulnasoftx.Output[[]SsisEnvironmentReferenceResponse]{
		OutputState: o.OutputState,
	}
}

func (o SsisEnvironmentReferenceResponseArrayOutput) Index(i khulnasoft.IntInput) SsisEnvironmentReferenceResponseOutput {
	return khulnasoft.All(o, i).ApplyT(func(vs []interface{}) SsisEnvironmentReferenceResponse {
		return vs[0].([]SsisEnvironmentReferenceResponse)[vs[1].(int)]
	}).(SsisEnvironmentReferenceResponseOutput)
}

// Ssis environment.
type SsisEnvironmentResponse struct {
	// Metadata description.
	Description *string `khulnasoft:"description"`
	// Folder id which contains environment.
	FolderId *float64 `khulnasoft:"folderId"`
	// Metadata id.
	Id *float64 `khulnasoft:"id"`
	// Metadata name.
	Name *string `khulnasoft:"name"`
	// The type of SSIS object metadata.
	// Expected value is 'Environment'.
	Type string `khulnasoft:"type"`
	// Variable in environment
	Variables []SsisVariableResponse `khulnasoft:"variables"`
}

// SsisEnvironmentResponseInput is an input type that accepts SsisEnvironmentResponseArgs and SsisEnvironmentResponseOutput values.
// You can construct a concrete instance of `SsisEnvironmentResponseInput` via:
//
//	SsisEnvironmentResponseArgs{...}
type SsisEnvironmentResponseInput interface {
	khulnasoft.Input

	ToSsisEnvironmentResponseOutput() SsisEnvironmentResponseOutput
	ToSsisEnvironmentResponseOutputWithContext(context.Context) SsisEnvironmentResponseOutput
}

// Ssis environment.
type SsisEnvironmentResponseArgs struct {
	// Metadata description.
	Description khulnasoft.StringPtrInput `khulnasoft:"description"`
	// Folder id which contains environment.
	FolderId khulnasoft.Float64PtrInput `khulnasoft:"folderId"`
	// Metadata id.
	Id khulnasoft.Float64PtrInput `khulnasoft:"id"`
	// Metadata name.
	Name khulnasoft.StringPtrInput `khulnasoft:"name"`
	// The type of SSIS object metadata.
	// Expected value is 'Environment'.
	Type khulnasoft.StringInput `khulnasoft:"type"`
	// Variable in environment
	Variables SsisVariableResponseArrayInput `khulnasoft:"variables"`
}

func (SsisEnvironmentResponseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SsisEnvironmentResponse)(nil)).Elem()
}

func (i SsisEnvironmentResponseArgs) ToSsisEnvironmentResponseOutput() SsisEnvironmentResponseOutput {
	return i.ToSsisEnvironmentResponseOutputWithContext(context.Background())
}

func (i SsisEnvironmentResponseArgs) ToSsisEnvironmentResponseOutputWithContext(ctx context.Context) SsisEnvironmentResponseOutput {
	return khulnasoft.ToOutputWithContext(ctx, i).(SsisEnvironmentResponseOutput)
}

func (i SsisEnvironmentResponseArgs) ToOutput(ctx context.Context) khulnasoftx.Output[SsisEnvironmentResponse] {
	return khulnasoftx.Output[SsisEnvironmentResponse]{
		OutputState: i.ToSsisEnvironmentResponseOutputWithContext(ctx).OutputState,
	}
}

// Ssis environment.
type SsisEnvironmentResponseOutput struct{ *khulnasoft.OutputState }

func (SsisEnvironmentResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SsisEnvironmentResponse)(nil)).Elem()
}

func (o SsisEnvironmentResponseOutput) ToSsisEnvironmentResponseOutput() SsisEnvironmentResponseOutput {
	return o
}

func (o SsisEnvironmentResponseOutput) ToSsisEnvironmentResponseOutputWithContext(ctx context.Context) SsisEnvironmentResponseOutput {
	return o
}

func (o SsisEnvironmentResponseOutput) ToOutput(ctx context.Context) khulnasoftx.Output[SsisEnvironmentResponse] {
	return khulnasoftx.Output[SsisEnvironmentResponse]{
		OutputState: o.OutputState,
	}
}

// Metadata description.
func (o SsisEnvironmentResponseOutput) Description() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisEnvironmentResponse) *string { return v.Description }).(khulnasoft.StringPtrOutput)
}

// Folder id which contains environment.
func (o SsisEnvironmentResponseOutput) FolderId() khulnasoft.Float64PtrOutput {
	return o.ApplyT(func(v SsisEnvironmentResponse) *float64 { return v.FolderId }).(khulnasoft.Float64PtrOutput)
}

// Metadata id.
func (o SsisEnvironmentResponseOutput) Id() khulnasoft.Float64PtrOutput {
	return o.ApplyT(func(v SsisEnvironmentResponse) *float64 { return v.Id }).(khulnasoft.Float64PtrOutput)
}

// Metadata name.
func (o SsisEnvironmentResponseOutput) Name() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisEnvironmentResponse) *string { return v.Name }).(khulnasoft.StringPtrOutput)
}

// The type of SSIS object metadata.
// Expected value is 'Environment'.
func (o SsisEnvironmentResponseOutput) Type() khulnasoft.StringOutput {
	return o.ApplyT(func(v SsisEnvironmentResponse) string { return v.Type }).(khulnasoft.StringOutput)
}

// Variable in environment
func (o SsisEnvironmentResponseOutput) Variables() SsisVariableResponseArrayOutput {
	return o.ApplyT(func(v SsisEnvironmentResponse) []SsisVariableResponse { return v.Variables }).(SsisVariableResponseArrayOutput)
}

// Ssis folder.
type SsisFolderResponse struct {
	// Metadata description.
	Description *string `khulnasoft:"description"`
	// Metadata id.
	Id *float64 `khulnasoft:"id"`
	// Metadata name.
	Name *string `khulnasoft:"name"`
	// The type of SSIS object metadata.
	// Expected value is 'Folder'.
	Type string `khulnasoft:"type"`
}

// SsisFolderResponseInput is an input type that accepts SsisFolderResponseArgs and SsisFolderResponseOutput values.
// You can construct a concrete instance of `SsisFolderResponseInput` via:
//
//	SsisFolderResponseArgs{...}
type SsisFolderResponseInput interface {
	khulnasoft.Input

	ToSsisFolderResponseOutput() SsisFolderResponseOutput
	ToSsisFolderResponseOutputWithContext(context.Context) SsisFolderResponseOutput
}

// Ssis folder.
type SsisFolderResponseArgs struct {
	// Metadata description.
	Description khulnasoft.StringPtrInput `khulnasoft:"description"`
	// Metadata id.
	Id khulnasoft.Float64PtrInput `khulnasoft:"id"`
	// Metadata name.
	Name khulnasoft.StringPtrInput `khulnasoft:"name"`
	// The type of SSIS object metadata.
	// Expected value is 'Folder'.
	Type khulnasoft.StringInput `khulnasoft:"type"`
}

func (SsisFolderResponseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SsisFolderResponse)(nil)).Elem()
}

func (i SsisFolderResponseArgs) ToSsisFolderResponseOutput() SsisFolderResponseOutput {
	return i.ToSsisFolderResponseOutputWithContext(context.Background())
}

func (i SsisFolderResponseArgs) ToSsisFolderResponseOutputWithContext(ctx context.Context) SsisFolderResponseOutput {
	return khulnasoft.ToOutputWithContext(ctx, i).(SsisFolderResponseOutput)
}

func (i SsisFolderResponseArgs) ToOutput(ctx context.Context) khulnasoftx.Output[SsisFolderResponse] {
	return khulnasoftx.Output[SsisFolderResponse]{
		OutputState: i.ToSsisFolderResponseOutputWithContext(ctx).OutputState,
	}
}

// Ssis folder.
type SsisFolderResponseOutput struct{ *khulnasoft.OutputState }

func (SsisFolderResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SsisFolderResponse)(nil)).Elem()
}

func (o SsisFolderResponseOutput) ToSsisFolderResponseOutput() SsisFolderResponseOutput {
	return o
}

func (o SsisFolderResponseOutput) ToSsisFolderResponseOutputWithContext(ctx context.Context) SsisFolderResponseOutput {
	return o
}

func (o SsisFolderResponseOutput) ToOutput(ctx context.Context) khulnasoftx.Output[SsisFolderResponse] {
	return khulnasoftx.Output[SsisFolderResponse]{
		OutputState: o.OutputState,
	}
}

// Metadata description.
func (o SsisFolderResponseOutput) Description() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisFolderResponse) *string { return v.Description }).(khulnasoft.StringPtrOutput)
}

// Metadata id.
func (o SsisFolderResponseOutput) Id() khulnasoft.Float64PtrOutput {
	return o.ApplyT(func(v SsisFolderResponse) *float64 { return v.Id }).(khulnasoft.Float64PtrOutput)
}

// Metadata name.
func (o SsisFolderResponseOutput) Name() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisFolderResponse) *string { return v.Name }).(khulnasoft.StringPtrOutput)
}

// The type of SSIS object metadata.
// Expected value is 'Folder'.
func (o SsisFolderResponseOutput) Type() khulnasoft.StringOutput {
	return o.ApplyT(func(v SsisFolderResponse) string { return v.Type }).(khulnasoft.StringOutput)
}

// Ssis Package.
type SsisPackageResponse struct {
	// Metadata description.
	Description *string `khulnasoft:"description"`
	// Folder id which contains package.
	FolderId *float64 `khulnasoft:"folderId"`
	// Metadata id.
	Id *float64 `khulnasoft:"id"`
	// Metadata name.
	Name *string `khulnasoft:"name"`
	// Parameters in package
	Parameters []SsisParameterResponse `khulnasoft:"parameters"`
	// Project id which contains package.
	ProjectId *float64 `khulnasoft:"projectId"`
	// Project version which contains package.
	ProjectVersion *float64 `khulnasoft:"projectVersion"`
	// The type of SSIS object metadata.
	// Expected value is 'Package'.
	Type string `khulnasoft:"type"`
}

// SsisPackageResponseInput is an input type that accepts SsisPackageResponseArgs and SsisPackageResponseOutput values.
// You can construct a concrete instance of `SsisPackageResponseInput` via:
//
//	SsisPackageResponseArgs{...}
type SsisPackageResponseInput interface {
	khulnasoft.Input

	ToSsisPackageResponseOutput() SsisPackageResponseOutput
	ToSsisPackageResponseOutputWithContext(context.Context) SsisPackageResponseOutput
}

// Ssis Package.
type SsisPackageResponseArgs struct {
	// Metadata description.
	Description khulnasoft.StringPtrInput `khulnasoft:"description"`
	// Folder id which contains package.
	FolderId khulnasoft.Float64PtrInput `khulnasoft:"folderId"`
	// Metadata id.
	Id khulnasoft.Float64PtrInput `khulnasoft:"id"`
	// Metadata name.
	Name khulnasoft.StringPtrInput `khulnasoft:"name"`
	// Parameters in package
	Parameters SsisParameterResponseArrayInput `khulnasoft:"parameters"`
	// Project id which contains package.
	ProjectId khulnasoft.Float64PtrInput `khulnasoft:"projectId"`
	// Project version which contains package.
	ProjectVersion khulnasoft.Float64PtrInput `khulnasoft:"projectVersion"`
	// The type of SSIS object metadata.
	// Expected value is 'Package'.
	Type khulnasoft.StringInput `khulnasoft:"type"`
}

func (SsisPackageResponseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SsisPackageResponse)(nil)).Elem()
}

func (i SsisPackageResponseArgs) ToSsisPackageResponseOutput() SsisPackageResponseOutput {
	return i.ToSsisPackageResponseOutputWithContext(context.Background())
}

func (i SsisPackageResponseArgs) ToSsisPackageResponseOutputWithContext(ctx context.Context) SsisPackageResponseOutput {
	return khulnasoft.ToOutputWithContext(ctx, i).(SsisPackageResponseOutput)
}

func (i SsisPackageResponseArgs) ToOutput(ctx context.Context) khulnasoftx.Output[SsisPackageResponse] {
	return khulnasoftx.Output[SsisPackageResponse]{
		OutputState: i.ToSsisPackageResponseOutputWithContext(ctx).OutputState,
	}
}

// Ssis Package.
type SsisPackageResponseOutput struct{ *khulnasoft.OutputState }

func (SsisPackageResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SsisPackageResponse)(nil)).Elem()
}

func (o SsisPackageResponseOutput) ToSsisPackageResponseOutput() SsisPackageResponseOutput {
	return o
}

func (o SsisPackageResponseOutput) ToSsisPackageResponseOutputWithContext(ctx context.Context) SsisPackageResponseOutput {
	return o
}

func (o SsisPackageResponseOutput) ToOutput(ctx context.Context) khulnasoftx.Output[SsisPackageResponse] {
	return khulnasoftx.Output[SsisPackageResponse]{
		OutputState: o.OutputState,
	}
}

// Metadata description.
func (o SsisPackageResponseOutput) Description() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisPackageResponse) *string { return v.Description }).(khulnasoft.StringPtrOutput)
}

// Folder id which contains package.
func (o SsisPackageResponseOutput) FolderId() khulnasoft.Float64PtrOutput {
	return o.ApplyT(func(v SsisPackageResponse) *float64 { return v.FolderId }).(khulnasoft.Float64PtrOutput)
}

// Metadata id.
func (o SsisPackageResponseOutput) Id() khulnasoft.Float64PtrOutput {
	return o.ApplyT(func(v SsisPackageResponse) *float64 { return v.Id }).(khulnasoft.Float64PtrOutput)
}

// Metadata name.
func (o SsisPackageResponseOutput) Name() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisPackageResponse) *string { return v.Name }).(khulnasoft.StringPtrOutput)
}

// Parameters in package
func (o SsisPackageResponseOutput) Parameters() SsisParameterResponseArrayOutput {
	return o.ApplyT(func(v SsisPackageResponse) []SsisParameterResponse { return v.Parameters }).(SsisParameterResponseArrayOutput)
}

// Project id which contains package.
func (o SsisPackageResponseOutput) ProjectId() khulnasoft.Float64PtrOutput {
	return o.ApplyT(func(v SsisPackageResponse) *float64 { return v.ProjectId }).(khulnasoft.Float64PtrOutput)
}

// Project version which contains package.
func (o SsisPackageResponseOutput) ProjectVersion() khulnasoft.Float64PtrOutput {
	return o.ApplyT(func(v SsisPackageResponse) *float64 { return v.ProjectVersion }).(khulnasoft.Float64PtrOutput)
}

// The type of SSIS object metadata.
// Expected value is 'Package'.
func (o SsisPackageResponseOutput) Type() khulnasoft.StringOutput {
	return o.ApplyT(func(v SsisPackageResponse) string { return v.Type }).(khulnasoft.StringOutput)
}

// Ssis parameter.
type SsisParameterResponse struct {
	// Parameter type.
	DataType *string `khulnasoft:"dataType"`
	// Default value of parameter.
	DefaultValue *string `khulnasoft:"defaultValue"`
	// Parameter description.
	Description *string `khulnasoft:"description"`
	// Design default value of parameter.
	DesignDefaultValue *string `khulnasoft:"designDefaultValue"`
	// Parameter id.
	Id *float64 `khulnasoft:"id"`
	// Parameter name.
	Name *string `khulnasoft:"name"`
	// Whether parameter is required.
	Required *bool `khulnasoft:"required"`
	// Whether parameter is sensitive.
	Sensitive *bool `khulnasoft:"sensitive"`
	// Default sensitive value of parameter.
	SensitiveDefaultValue *string `khulnasoft:"sensitiveDefaultValue"`
	// Parameter value set.
	ValueSet *bool `khulnasoft:"valueSet"`
	// Parameter value type.
	ValueType *string `khulnasoft:"valueType"`
	// Parameter reference variable.
	Variable *string `khulnasoft:"variable"`
}

// SsisParameterResponseInput is an input type that accepts SsisParameterResponseArgs and SsisParameterResponseOutput values.
// You can construct a concrete instance of `SsisParameterResponseInput` via:
//
//	SsisParameterResponseArgs{...}
type SsisParameterResponseInput interface {
	khulnasoft.Input

	ToSsisParameterResponseOutput() SsisParameterResponseOutput
	ToSsisParameterResponseOutputWithContext(context.Context) SsisParameterResponseOutput
}

// Ssis parameter.
type SsisParameterResponseArgs struct {
	// Parameter type.
	DataType khulnasoft.StringPtrInput `khulnasoft:"dataType"`
	// Default value of parameter.
	DefaultValue khulnasoft.StringPtrInput `khulnasoft:"defaultValue"`
	// Parameter description.
	Description khulnasoft.StringPtrInput `khulnasoft:"description"`
	// Design default value of parameter.
	DesignDefaultValue khulnasoft.StringPtrInput `khulnasoft:"designDefaultValue"`
	// Parameter id.
	Id khulnasoft.Float64PtrInput `khulnasoft:"id"`
	// Parameter name.
	Name khulnasoft.StringPtrInput `khulnasoft:"name"`
	// Whether parameter is required.
	Required khulnasoft.BoolPtrInput `khulnasoft:"required"`
	// Whether parameter is sensitive.
	Sensitive khulnasoft.BoolPtrInput `khulnasoft:"sensitive"`
	// Default sensitive value of parameter.
	SensitiveDefaultValue khulnasoft.StringPtrInput `khulnasoft:"sensitiveDefaultValue"`
	// Parameter value set.
	ValueSet khulnasoft.BoolPtrInput `khulnasoft:"valueSet"`
	// Parameter value type.
	ValueType khulnasoft.StringPtrInput `khulnasoft:"valueType"`
	// Parameter reference variable.
	Variable khulnasoft.StringPtrInput `khulnasoft:"variable"`
}

func (SsisParameterResponseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SsisParameterResponse)(nil)).Elem()
}

func (i SsisParameterResponseArgs) ToSsisParameterResponseOutput() SsisParameterResponseOutput {
	return i.ToSsisParameterResponseOutputWithContext(context.Background())
}

func (i SsisParameterResponseArgs) ToSsisParameterResponseOutputWithContext(ctx context.Context) SsisParameterResponseOutput {
	return khulnasoft.ToOutputWithContext(ctx, i).(SsisParameterResponseOutput)
}

func (i SsisParameterResponseArgs) ToOutput(ctx context.Context) khulnasoftx.Output[SsisParameterResponse] {
	return khulnasoftx.Output[SsisParameterResponse]{
		OutputState: i.ToSsisParameterResponseOutputWithContext(ctx).OutputState,
	}
}

// SsisParameterResponseArrayInput is an input type that accepts SsisParameterResponseArray and SsisParameterResponseArrayOutput values.
// You can construct a concrete instance of `SsisParameterResponseArrayInput` via:
//
//	SsisParameterResponseArray{ SsisParameterResponseArgs{...} }
type SsisParameterResponseArrayInput interface {
	khulnasoft.Input

	ToSsisParameterResponseArrayOutput() SsisParameterResponseArrayOutput
	ToSsisParameterResponseArrayOutputWithContext(context.Context) SsisParameterResponseArrayOutput
}

type SsisParameterResponseArray []SsisParameterResponseInput

func (SsisParameterResponseArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SsisParameterResponse)(nil)).Elem()
}

func (i SsisParameterResponseArray) ToSsisParameterResponseArrayOutput() SsisParameterResponseArrayOutput {
	return i.ToSsisParameterResponseArrayOutputWithContext(context.Background())
}

func (i SsisParameterResponseArray) ToSsisParameterResponseArrayOutputWithContext(ctx context.Context) SsisParameterResponseArrayOutput {
	return khulnasoft.ToOutputWithContext(ctx, i).(SsisParameterResponseArrayOutput)
}

func (i SsisParameterResponseArray) ToOutput(ctx context.Context) khulnasoftx.Output[[]SsisParameterResponse] {
	return khulnasoftx.Output[[]SsisParameterResponse]{
		OutputState: i.ToSsisParameterResponseArrayOutputWithContext(ctx).OutputState,
	}
}

// Ssis parameter.
type SsisParameterResponseOutput struct{ *khulnasoft.OutputState }

func (SsisParameterResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SsisParameterResponse)(nil)).Elem()
}

func (o SsisParameterResponseOutput) ToSsisParameterResponseOutput() SsisParameterResponseOutput {
	return o
}

func (o SsisParameterResponseOutput) ToSsisParameterResponseOutputWithContext(ctx context.Context) SsisParameterResponseOutput {
	return o
}

func (o SsisParameterResponseOutput) ToOutput(ctx context.Context) khulnasoftx.Output[SsisParameterResponse] {
	return khulnasoftx.Output[SsisParameterResponse]{
		OutputState: o.OutputState,
	}
}

// Parameter type.
func (o SsisParameterResponseOutput) DataType() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisParameterResponse) *string { return v.DataType }).(khulnasoft.StringPtrOutput)
}

// Default value of parameter.
func (o SsisParameterResponseOutput) DefaultValue() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisParameterResponse) *string { return v.DefaultValue }).(khulnasoft.StringPtrOutput)
}

// Parameter description.
func (o SsisParameterResponseOutput) Description() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisParameterResponse) *string { return v.Description }).(khulnasoft.StringPtrOutput)
}

// Design default value of parameter.
func (o SsisParameterResponseOutput) DesignDefaultValue() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisParameterResponse) *string { return v.DesignDefaultValue }).(khulnasoft.StringPtrOutput)
}

// Parameter id.
func (o SsisParameterResponseOutput) Id() khulnasoft.Float64PtrOutput {
	return o.ApplyT(func(v SsisParameterResponse) *float64 { return v.Id }).(khulnasoft.Float64PtrOutput)
}

// Parameter name.
func (o SsisParameterResponseOutput) Name() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisParameterResponse) *string { return v.Name }).(khulnasoft.StringPtrOutput)
}

// Whether parameter is required.
func (o SsisParameterResponseOutput) Required() khulnasoft.BoolPtrOutput {
	return o.ApplyT(func(v SsisParameterResponse) *bool { return v.Required }).(khulnasoft.BoolPtrOutput)
}

// Whether parameter is sensitive.
func (o SsisParameterResponseOutput) Sensitive() khulnasoft.BoolPtrOutput {
	return o.ApplyT(func(v SsisParameterResponse) *bool { return v.Sensitive }).(khulnasoft.BoolPtrOutput)
}

// Default sensitive value of parameter.
func (o SsisParameterResponseOutput) SensitiveDefaultValue() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisParameterResponse) *string { return v.SensitiveDefaultValue }).(khulnasoft.StringPtrOutput)
}

// Parameter value set.
func (o SsisParameterResponseOutput) ValueSet() khulnasoft.BoolPtrOutput {
	return o.ApplyT(func(v SsisParameterResponse) *bool { return v.ValueSet }).(khulnasoft.BoolPtrOutput)
}

// Parameter value type.
func (o SsisParameterResponseOutput) ValueType() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisParameterResponse) *string { return v.ValueType }).(khulnasoft.StringPtrOutput)
}

// Parameter reference variable.
func (o SsisParameterResponseOutput) Variable() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisParameterResponse) *string { return v.Variable }).(khulnasoft.StringPtrOutput)
}

type SsisParameterResponseArrayOutput struct{ *khulnasoft.OutputState }

func (SsisParameterResponseArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SsisParameterResponse)(nil)).Elem()
}

func (o SsisParameterResponseArrayOutput) ToSsisParameterResponseArrayOutput() SsisParameterResponseArrayOutput {
	return o
}

func (o SsisParameterResponseArrayOutput) ToSsisParameterResponseArrayOutputWithContext(ctx context.Context) SsisParameterResponseArrayOutput {
	return o
}

func (o SsisParameterResponseArrayOutput) ToOutput(ctx context.Context) khulnasoftx.Output[[]SsisParameterResponse] {
	return khulnasoftx.Output[[]SsisParameterResponse]{
		OutputState: o.OutputState,
	}
}

func (o SsisParameterResponseArrayOutput) Index(i khulnasoft.IntInput) SsisParameterResponseOutput {
	return khulnasoft.All(o, i).ApplyT(func(vs []interface{}) SsisParameterResponse {
		return vs[0].([]SsisParameterResponse)[vs[1].(int)]
	}).(SsisParameterResponseOutput)
}

// Ssis project.
type SsisProjectResponse struct {
	// Metadata description.
	Description *string `khulnasoft:"description"`
	// Environment reference in project
	EnvironmentRefs []SsisEnvironmentReferenceResponse `khulnasoft:"environmentRefs"`
	// Folder id which contains project.
	FolderId *float64 `khulnasoft:"folderId"`
	// Metadata id.
	Id *float64 `khulnasoft:"id"`
	// Metadata name.
	Name *string `khulnasoft:"name"`
	// Parameters in project
	Parameters []SsisParameterResponse `khulnasoft:"parameters"`
	// The type of SSIS object metadata.
	// Expected value is 'Project'.
	Type string `khulnasoft:"type"`
	// Project version.
	Version *float64 `khulnasoft:"version"`
}

// SsisProjectResponseInput is an input type that accepts SsisProjectResponseArgs and SsisProjectResponseOutput values.
// You can construct a concrete instance of `SsisProjectResponseInput` via:
//
//	SsisProjectResponseArgs{...}
type SsisProjectResponseInput interface {
	khulnasoft.Input

	ToSsisProjectResponseOutput() SsisProjectResponseOutput
	ToSsisProjectResponseOutputWithContext(context.Context) SsisProjectResponseOutput
}

// Ssis project.
type SsisProjectResponseArgs struct {
	// Metadata description.
	Description khulnasoft.StringPtrInput `khulnasoft:"description"`
	// Environment reference in project
	EnvironmentRefs SsisEnvironmentReferenceResponseArrayInput `khulnasoft:"environmentRefs"`
	// Folder id which contains project.
	FolderId khulnasoft.Float64PtrInput `khulnasoft:"folderId"`
	// Metadata id.
	Id khulnasoft.Float64PtrInput `khulnasoft:"id"`
	// Metadata name.
	Name khulnasoft.StringPtrInput `khulnasoft:"name"`
	// Parameters in project
	Parameters SsisParameterResponseArrayInput `khulnasoft:"parameters"`
	// The type of SSIS object metadata.
	// Expected value is 'Project'.
	Type khulnasoft.StringInput `khulnasoft:"type"`
	// Project version.
	Version khulnasoft.Float64PtrInput `khulnasoft:"version"`
}

func (SsisProjectResponseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SsisProjectResponse)(nil)).Elem()
}

func (i SsisProjectResponseArgs) ToSsisProjectResponseOutput() SsisProjectResponseOutput {
	return i.ToSsisProjectResponseOutputWithContext(context.Background())
}

func (i SsisProjectResponseArgs) ToSsisProjectResponseOutputWithContext(ctx context.Context) SsisProjectResponseOutput {
	return khulnasoft.ToOutputWithContext(ctx, i).(SsisProjectResponseOutput)
}

func (i SsisProjectResponseArgs) ToOutput(ctx context.Context) khulnasoftx.Output[SsisProjectResponse] {
	return khulnasoftx.Output[SsisProjectResponse]{
		OutputState: i.ToSsisProjectResponseOutputWithContext(ctx).OutputState,
	}
}

// Ssis project.
type SsisProjectResponseOutput struct{ *khulnasoft.OutputState }

func (SsisProjectResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SsisProjectResponse)(nil)).Elem()
}

func (o SsisProjectResponseOutput) ToSsisProjectResponseOutput() SsisProjectResponseOutput {
	return o
}

func (o SsisProjectResponseOutput) ToSsisProjectResponseOutputWithContext(ctx context.Context) SsisProjectResponseOutput {
	return o
}

func (o SsisProjectResponseOutput) ToOutput(ctx context.Context) khulnasoftx.Output[SsisProjectResponse] {
	return khulnasoftx.Output[SsisProjectResponse]{
		OutputState: o.OutputState,
	}
}

// Metadata description.
func (o SsisProjectResponseOutput) Description() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisProjectResponse) *string { return v.Description }).(khulnasoft.StringPtrOutput)
}

// Environment reference in project
func (o SsisProjectResponseOutput) EnvironmentRefs() SsisEnvironmentReferenceResponseArrayOutput {
	return o.ApplyT(func(v SsisProjectResponse) []SsisEnvironmentReferenceResponse { return v.EnvironmentRefs }).(SsisEnvironmentReferenceResponseArrayOutput)
}

// Folder id which contains project.
func (o SsisProjectResponseOutput) FolderId() khulnasoft.Float64PtrOutput {
	return o.ApplyT(func(v SsisProjectResponse) *float64 { return v.FolderId }).(khulnasoft.Float64PtrOutput)
}

// Metadata id.
func (o SsisProjectResponseOutput) Id() khulnasoft.Float64PtrOutput {
	return o.ApplyT(func(v SsisProjectResponse) *float64 { return v.Id }).(khulnasoft.Float64PtrOutput)
}

// Metadata name.
func (o SsisProjectResponseOutput) Name() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisProjectResponse) *string { return v.Name }).(khulnasoft.StringPtrOutput)
}

// Parameters in project
func (o SsisProjectResponseOutput) Parameters() SsisParameterResponseArrayOutput {
	return o.ApplyT(func(v SsisProjectResponse) []SsisParameterResponse { return v.Parameters }).(SsisParameterResponseArrayOutput)
}

// The type of SSIS object metadata.
// Expected value is 'Project'.
func (o SsisProjectResponseOutput) Type() khulnasoft.StringOutput {
	return o.ApplyT(func(v SsisProjectResponse) string { return v.Type }).(khulnasoft.StringOutput)
}

// Project version.
func (o SsisProjectResponseOutput) Version() khulnasoft.Float64PtrOutput {
	return o.ApplyT(func(v SsisProjectResponse) *float64 { return v.Version }).(khulnasoft.Float64PtrOutput)
}

// Ssis variable.
type SsisVariableResponse struct {
	// Variable type.
	DataType *string `khulnasoft:"dataType"`
	// Variable description.
	Description *string `khulnasoft:"description"`
	// Variable id.
	Id *float64 `khulnasoft:"id"`
	// Variable name.
	Name *string `khulnasoft:"name"`
	// Whether variable is sensitive.
	Sensitive *bool `khulnasoft:"sensitive"`
	// Variable sensitive value.
	SensitiveValue *string `khulnasoft:"sensitiveValue"`
	// Variable value.
	Value *string `khulnasoft:"value"`
}

// SsisVariableResponseInput is an input type that accepts SsisVariableResponseArgs and SsisVariableResponseOutput values.
// You can construct a concrete instance of `SsisVariableResponseInput` via:
//
//	SsisVariableResponseArgs{...}
type SsisVariableResponseInput interface {
	khulnasoft.Input

	ToSsisVariableResponseOutput() SsisVariableResponseOutput
	ToSsisVariableResponseOutputWithContext(context.Context) SsisVariableResponseOutput
}

// Ssis variable.
type SsisVariableResponseArgs struct {
	// Variable type.
	DataType khulnasoft.StringPtrInput `khulnasoft:"dataType"`
	// Variable description.
	Description khulnasoft.StringPtrInput `khulnasoft:"description"`
	// Variable id.
	Id khulnasoft.Float64PtrInput `khulnasoft:"id"`
	// Variable name.
	Name khulnasoft.StringPtrInput `khulnasoft:"name"`
	// Whether variable is sensitive.
	Sensitive khulnasoft.BoolPtrInput `khulnasoft:"sensitive"`
	// Variable sensitive value.
	SensitiveValue khulnasoft.StringPtrInput `khulnasoft:"sensitiveValue"`
	// Variable value.
	Value khulnasoft.StringPtrInput `khulnasoft:"value"`
}

func (SsisVariableResponseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SsisVariableResponse)(nil)).Elem()
}

func (i SsisVariableResponseArgs) ToSsisVariableResponseOutput() SsisVariableResponseOutput {
	return i.ToSsisVariableResponseOutputWithContext(context.Background())
}

func (i SsisVariableResponseArgs) ToSsisVariableResponseOutputWithContext(ctx context.Context) SsisVariableResponseOutput {
	return khulnasoft.ToOutputWithContext(ctx, i).(SsisVariableResponseOutput)
}

func (i SsisVariableResponseArgs) ToOutput(ctx context.Context) khulnasoftx.Output[SsisVariableResponse] {
	return khulnasoftx.Output[SsisVariableResponse]{
		OutputState: i.ToSsisVariableResponseOutputWithContext(ctx).OutputState,
	}
}

// SsisVariableResponseArrayInput is an input type that accepts SsisVariableResponseArray and SsisVariableResponseArrayOutput values.
// You can construct a concrete instance of `SsisVariableResponseArrayInput` via:
//
//	SsisVariableResponseArray{ SsisVariableResponseArgs{...} }
type SsisVariableResponseArrayInput interface {
	khulnasoft.Input

	ToSsisVariableResponseArrayOutput() SsisVariableResponseArrayOutput
	ToSsisVariableResponseArrayOutputWithContext(context.Context) SsisVariableResponseArrayOutput
}

type SsisVariableResponseArray []SsisVariableResponseInput

func (SsisVariableResponseArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SsisVariableResponse)(nil)).Elem()
}

func (i SsisVariableResponseArray) ToSsisVariableResponseArrayOutput() SsisVariableResponseArrayOutput {
	return i.ToSsisVariableResponseArrayOutputWithContext(context.Background())
}

func (i SsisVariableResponseArray) ToSsisVariableResponseArrayOutputWithContext(ctx context.Context) SsisVariableResponseArrayOutput {
	return khulnasoft.ToOutputWithContext(ctx, i).(SsisVariableResponseArrayOutput)
}

func (i SsisVariableResponseArray) ToOutput(ctx context.Context) khulnasoftx.Output[[]SsisVariableResponse] {
	return khulnasoftx.Output[[]SsisVariableResponse]{
		OutputState: i.ToSsisVariableResponseArrayOutputWithContext(ctx).OutputState,
	}
}

// Ssis variable.
type SsisVariableResponseOutput struct{ *khulnasoft.OutputState }

func (SsisVariableResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SsisVariableResponse)(nil)).Elem()
}

func (o SsisVariableResponseOutput) ToSsisVariableResponseOutput() SsisVariableResponseOutput {
	return o
}

func (o SsisVariableResponseOutput) ToSsisVariableResponseOutputWithContext(ctx context.Context) SsisVariableResponseOutput {
	return o
}

func (o SsisVariableResponseOutput) ToOutput(ctx context.Context) khulnasoftx.Output[SsisVariableResponse] {
	return khulnasoftx.Output[SsisVariableResponse]{
		OutputState: o.OutputState,
	}
}

// Variable type.
func (o SsisVariableResponseOutput) DataType() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisVariableResponse) *string { return v.DataType }).(khulnasoft.StringPtrOutput)
}

// Variable description.
func (o SsisVariableResponseOutput) Description() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisVariableResponse) *string { return v.Description }).(khulnasoft.StringPtrOutput)
}

// Variable id.
func (o SsisVariableResponseOutput) Id() khulnasoft.Float64PtrOutput {
	return o.ApplyT(func(v SsisVariableResponse) *float64 { return v.Id }).(khulnasoft.Float64PtrOutput)
}

// Variable name.
func (o SsisVariableResponseOutput) Name() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisVariableResponse) *string { return v.Name }).(khulnasoft.StringPtrOutput)
}

// Whether variable is sensitive.
func (o SsisVariableResponseOutput) Sensitive() khulnasoft.BoolPtrOutput {
	return o.ApplyT(func(v SsisVariableResponse) *bool { return v.Sensitive }).(khulnasoft.BoolPtrOutput)
}

// Variable sensitive value.
func (o SsisVariableResponseOutput) SensitiveValue() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisVariableResponse) *string { return v.SensitiveValue }).(khulnasoft.StringPtrOutput)
}

// Variable value.
func (o SsisVariableResponseOutput) Value() khulnasoft.StringPtrOutput {
	return o.ApplyT(func(v SsisVariableResponse) *string { return v.Value }).(khulnasoft.StringPtrOutput)
}

type SsisVariableResponseArrayOutput struct{ *khulnasoft.OutputState }

func (SsisVariableResponseArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SsisVariableResponse)(nil)).Elem()
}

func (o SsisVariableResponseArrayOutput) ToSsisVariableResponseArrayOutput() SsisVariableResponseArrayOutput {
	return o
}

func (o SsisVariableResponseArrayOutput) ToSsisVariableResponseArrayOutputWithContext(ctx context.Context) SsisVariableResponseArrayOutput {
	return o
}

func (o SsisVariableResponseArrayOutput) ToOutput(ctx context.Context) khulnasoftx.Output[[]SsisVariableResponse] {
	return khulnasoftx.Output[[]SsisVariableResponse]{
		OutputState: o.OutputState,
	}
}

func (o SsisVariableResponseArrayOutput) Index(i khulnasoft.IntInput) SsisVariableResponseOutput {
	return khulnasoft.All(o, i).ApplyT(func(vs []interface{}) SsisVariableResponse {
		return vs[0].([]SsisVariableResponse)[vs[1].(int)]
	}).(SsisVariableResponseOutput)
}

// An access key for the storage account.
type StorageAccountKeyResponse struct {
	// Creation time of the key, in round trip date format.
	CreationTime string `khulnasoft:"creationTime"`
	// Name of the key.
	KeyName string `khulnasoft:"keyName"`
	// Permissions for the key -- read-only or full permissions.
	Permissions string `khulnasoft:"permissions"`
	// Base 64-encoded value of the key.
	Value string `khulnasoft:"value"`
}

// StorageAccountKeyResponseInput is an input type that accepts StorageAccountKeyResponseArgs and StorageAccountKeyResponseOutput values.
// You can construct a concrete instance of `StorageAccountKeyResponseInput` via:
//
//	StorageAccountKeyResponseArgs{...}
type StorageAccountKeyResponseInput interface {
	khulnasoft.Input

	ToStorageAccountKeyResponseOutput() StorageAccountKeyResponseOutput
	ToStorageAccountKeyResponseOutputWithContext(context.Context) StorageAccountKeyResponseOutput
}

// An access key for the storage account.
type StorageAccountKeyResponseArgs struct {
	// Creation time of the key, in round trip date format.
	CreationTime khulnasoft.StringInput `khulnasoft:"creationTime"`
	// Name of the key.
	KeyName khulnasoft.StringInput `khulnasoft:"keyName"`
	// Permissions for the key -- read-only or full permissions.
	Permissions khulnasoft.StringInput `khulnasoft:"permissions"`
	// Base 64-encoded value of the key.
	Value khulnasoft.StringInput `khulnasoft:"value"`
}

func (StorageAccountKeyResponseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*StorageAccountKeyResponse)(nil)).Elem()
}

func (i StorageAccountKeyResponseArgs) ToStorageAccountKeyResponseOutput() StorageAccountKeyResponseOutput {
	return i.ToStorageAccountKeyResponseOutputWithContext(context.Background())
}

func (i StorageAccountKeyResponseArgs) ToStorageAccountKeyResponseOutputWithContext(ctx context.Context) StorageAccountKeyResponseOutput {
	return khulnasoft.ToOutputWithContext(ctx, i).(StorageAccountKeyResponseOutput)
}

func (i StorageAccountKeyResponseArgs) ToOutput(ctx context.Context) khulnasoftx.Output[StorageAccountKeyResponse] {
	return khulnasoftx.Output[StorageAccountKeyResponse]{
		OutputState: i.ToStorageAccountKeyResponseOutputWithContext(ctx).OutputState,
	}
}

// StorageAccountKeyResponseArrayInput is an input type that accepts StorageAccountKeyResponseArray and StorageAccountKeyResponseArrayOutput values.
// You can construct a concrete instance of `StorageAccountKeyResponseArrayInput` via:
//
//	StorageAccountKeyResponseArray{ StorageAccountKeyResponseArgs{...} }
type StorageAccountKeyResponseArrayInput interface {
	khulnasoft.Input

	ToStorageAccountKeyResponseArrayOutput() StorageAccountKeyResponseArrayOutput
	ToStorageAccountKeyResponseArrayOutputWithContext(context.Context) StorageAccountKeyResponseArrayOutput
}

type StorageAccountKeyResponseArray []StorageAccountKeyResponseInput

func (StorageAccountKeyResponseArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]StorageAccountKeyResponse)(nil)).Elem()
}

func (i StorageAccountKeyResponseArray) ToStorageAccountKeyResponseArrayOutput() StorageAccountKeyResponseArrayOutput {
	return i.ToStorageAccountKeyResponseArrayOutputWithContext(context.Background())
}

func (i StorageAccountKeyResponseArray) ToStorageAccountKeyResponseArrayOutputWithContext(ctx context.Context) StorageAccountKeyResponseArrayOutput {
	return khulnasoft.ToOutputWithContext(ctx, i).(StorageAccountKeyResponseArrayOutput)
}

func (i StorageAccountKeyResponseArray) ToOutput(ctx context.Context) khulnasoftx.Output[[]StorageAccountKeyResponse] {
	return khulnasoftx.Output[[]StorageAccountKeyResponse]{
		OutputState: i.ToStorageAccountKeyResponseArrayOutputWithContext(ctx).OutputState,
	}
}

// An access key for the storage account.
type StorageAccountKeyResponseOutput struct{ *khulnasoft.OutputState }

func (StorageAccountKeyResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*StorageAccountKeyResponse)(nil)).Elem()
}

func (o StorageAccountKeyResponseOutput) ToStorageAccountKeyResponseOutput() StorageAccountKeyResponseOutput {
	return o
}

func (o StorageAccountKeyResponseOutput) ToStorageAccountKeyResponseOutputWithContext(ctx context.Context) StorageAccountKeyResponseOutput {
	return o
}

func (o StorageAccountKeyResponseOutput) ToOutput(ctx context.Context) khulnasoftx.Output[StorageAccountKeyResponse] {
	return khulnasoftx.Output[StorageAccountKeyResponse]{
		OutputState: o.OutputState,
	}
}

// Creation time of the key, in round trip date format.
func (o StorageAccountKeyResponseOutput) CreationTime() khulnasoft.StringOutput {
	return o.ApplyT(func(v StorageAccountKeyResponse) string { return v.CreationTime }).(khulnasoft.StringOutput)
}

// Name of the key.
func (o StorageAccountKeyResponseOutput) KeyName() khulnasoft.StringOutput {
	return o.ApplyT(func(v StorageAccountKeyResponse) string { return v.KeyName }).(khulnasoft.StringOutput)
}

// Permissions for the key -- read-only or full permissions.
func (o StorageAccountKeyResponseOutput) Permissions() khulnasoft.StringOutput {
	return o.ApplyT(func(v StorageAccountKeyResponse) string { return v.Permissions }).(khulnasoft.StringOutput)
}

// Base 64-encoded value of the key.
func (o StorageAccountKeyResponseOutput) Value() khulnasoft.StringOutput {
	return o.ApplyT(func(v StorageAccountKeyResponse) string { return v.Value }).(khulnasoft.StringOutput)
}

type StorageAccountKeyResponseArrayOutput struct{ *khulnasoft.OutputState }

func (StorageAccountKeyResponseArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]StorageAccountKeyResponse)(nil)).Elem()
}

func (o StorageAccountKeyResponseArrayOutput) ToStorageAccountKeyResponseArrayOutput() StorageAccountKeyResponseArrayOutput {
	return o
}

func (o StorageAccountKeyResponseArrayOutput) ToStorageAccountKeyResponseArrayOutputWithContext(ctx context.Context) StorageAccountKeyResponseArrayOutput {
	return o
}

func (o StorageAccountKeyResponseArrayOutput) ToOutput(ctx context.Context) khulnasoftx.Output[[]StorageAccountKeyResponse] {
	return khulnasoftx.Output[[]StorageAccountKeyResponse]{
		OutputState: o.OutputState,
	}
}

func (o StorageAccountKeyResponseArrayOutput) Index(i khulnasoft.IntInput) StorageAccountKeyResponseOutput {
	return khulnasoft.All(o, i).ApplyT(func(vs []interface{}) StorageAccountKeyResponse {
		return vs[0].([]StorageAccountKeyResponse)[vs[1].(int)]
	}).(StorageAccountKeyResponseOutput)
}

func init() {
	khulnasoft.RegisterInputType(reflect.TypeOf((*BastionShareableLinkInput)(nil)).Elem(), BastionShareableLinkArgs{})
	khulnasoft.RegisterInputType(reflect.TypeOf((*BastionShareableLinkArrayInput)(nil)).Elem(), BastionShareableLinkArray{})
	khulnasoft.RegisterInputType(reflect.TypeOf((*SsisEnvironmentReferenceResponseInput)(nil)).Elem(), SsisEnvironmentReferenceResponseArgs{})
	khulnasoft.RegisterInputType(reflect.TypeOf((*SsisEnvironmentReferenceResponseArrayInput)(nil)).Elem(), SsisEnvironmentReferenceResponseArray{})
	khulnasoft.RegisterInputType(reflect.TypeOf((*SsisEnvironmentResponseInput)(nil)).Elem(), SsisEnvironmentResponseArgs{})
	khulnasoft.RegisterInputType(reflect.TypeOf((*SsisFolderResponseInput)(nil)).Elem(), SsisFolderResponseArgs{})
	khulnasoft.RegisterInputType(reflect.TypeOf((*SsisPackageResponseInput)(nil)).Elem(), SsisPackageResponseArgs{})
	khulnasoft.RegisterInputType(reflect.TypeOf((*SsisParameterResponseInput)(nil)).Elem(), SsisParameterResponseArgs{})
	khulnasoft.RegisterInputType(reflect.TypeOf((*SsisParameterResponseArrayInput)(nil)).Elem(), SsisParameterResponseArray{})
	khulnasoft.RegisterInputType(reflect.TypeOf((*SsisProjectResponseInput)(nil)).Elem(), SsisProjectResponseArgs{})
	khulnasoft.RegisterInputType(reflect.TypeOf((*SsisVariableResponseInput)(nil)).Elem(), SsisVariableResponseArgs{})
	khulnasoft.RegisterInputType(reflect.TypeOf((*SsisVariableResponseArrayInput)(nil)).Elem(), SsisVariableResponseArray{})
	khulnasoft.RegisterInputType(reflect.TypeOf((*StorageAccountKeyResponseInput)(nil)).Elem(), StorageAccountKeyResponseArgs{})
	khulnasoft.RegisterInputType(reflect.TypeOf((*StorageAccountKeyResponseArrayInput)(nil)).Elem(), StorageAccountKeyResponseArray{})
	khulnasoft.RegisterOutputType(BastionShareableLinkOutput{})
	khulnasoft.RegisterOutputType(BastionShareableLinkArrayOutput{})
	khulnasoft.RegisterOutputType(SsisEnvironmentReferenceResponseOutput{})
	khulnasoft.RegisterOutputType(SsisEnvironmentReferenceResponseArrayOutput{})
	khulnasoft.RegisterOutputType(SsisEnvironmentResponseOutput{})
	khulnasoft.RegisterOutputType(SsisFolderResponseOutput{})
	khulnasoft.RegisterOutputType(SsisPackageResponseOutput{})
	khulnasoft.RegisterOutputType(SsisParameterResponseOutput{})
	khulnasoft.RegisterOutputType(SsisParameterResponseArrayOutput{})
	khulnasoft.RegisterOutputType(SsisProjectResponseOutput{})
	khulnasoft.RegisterOutputType(SsisVariableResponseOutput{})
	khulnasoft.RegisterOutputType(SsisVariableResponseArrayOutput{})
	khulnasoft.RegisterOutputType(StorageAccountKeyResponseOutput{})
	khulnasoft.RegisterOutputType(StorageAccountKeyResponseArrayOutput{})
}
