# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import khulnasoft
import khulnasoft.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'InnerType',
]

@khulnasoft.output_type
class InnerType(dict):
    """
    It's fine to use urn and id in nested objects
    """
    def __init__(__self__, *,
                 id: Optional[str] = None,
                 urn: Optional[str] = None):
        """
        It's fine to use urn and id in nested objects
        """
        if id is not None:
            khulnasoft.set(__self__, "id", id)
        if urn is not None:
            khulnasoft.set(__self__, "urn", urn)

    @property
    @khulnasoft.getter
    def id(self) -> Optional[str]:
        return khulnasoft.get(self, "id")

    @property
    @khulnasoft.getter
    def urn(self) -> Optional[str]:
        return khulnasoft.get(self, "urn")


