// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package example

import (
	"context"
	"reflect"

	"external-resource-schema/example/internal"
	"github.com/khulnasoft/khulnasoft-random/sdk/v4/go/random"
	"github.com/khulnasoft/khulnasoft/sdk/v3/go/khulnasoft"
)

func ArgFunction(ctx *khulnasoft.Context, args *ArgFunctionArgs, opts ...khulnasoft.InvokeOption) (*ArgFunctionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ArgFunctionResult
	err := ctx.Invoke("example::argFunction", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ArgFunctionArgs struct {
	Name *random.RandomPet `khulnasoft:"name"`
}

type ArgFunctionResult struct {
	Age *int `khulnasoft:"age"`
}

func ArgFunctionOutput(ctx *khulnasoft.Context, args ArgFunctionOutputArgs, opts ...khulnasoft.InvokeOption) ArgFunctionResultOutput {
	return khulnasoft.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ArgFunctionResultOutput, error) {
			args := v.(ArgFunctionArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv ArgFunctionResult
			secret, err := ctx.InvokePackageRaw("example::argFunction", args, &rv, "", opts...)
			if err != nil {
				return ArgFunctionResultOutput{}, err
			}

			output := khulnasoft.ToOutput(rv).(ArgFunctionResultOutput)
			if secret {
				return khulnasoft.ToSecret(output).(ArgFunctionResultOutput), nil
			}
			return output, nil
		}).(ArgFunctionResultOutput)
}

type ArgFunctionOutputArgs struct {
	Name random.RandomPetInput `khulnasoft:"name"`
}

func (ArgFunctionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ArgFunctionArgs)(nil)).Elem()
}

type ArgFunctionResultOutput struct{ *khulnasoft.OutputState }

func (ArgFunctionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ArgFunctionResult)(nil)).Elem()
}

func (o ArgFunctionResultOutput) ToArgFunctionResultOutput() ArgFunctionResultOutput {
	return o
}

func (o ArgFunctionResultOutput) ToArgFunctionResultOutputWithContext(ctx context.Context) ArgFunctionResultOutput {
	return o
}

func (o ArgFunctionResultOutput) Age() khulnasoft.IntPtrOutput {
	return o.ApplyT(func(v ArgFunctionResult) *int { return v.Age }).(khulnasoft.IntPtrOutput)
}

func init() {
	khulnasoft.RegisterOutputType(ArgFunctionResultOutput{})
}
