/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { KhulnasoftCore } from "../core.js";
import { messagesDelete } from "../funcs/messagesDelete.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useKhulnasoftContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type MessagesDeleteMutationVariables = {
  messageId: string;
  idempotencyKey?: string | undefined;
  options?: RequestOptions;
};

export type MessagesDeleteMutationData =
  operations.MessagesControllerDeleteMessageResponse;

/**
 * Delete message
 *
 * @remarks
 * Deletes a message entity from the Khulnasoft platform
 */
export function useMessagesDeleteMutation(
  options?: MutationHookOptions<
    MessagesDeleteMutationData,
    Error,
    MessagesDeleteMutationVariables
  >,
): UseMutationResult<
  MessagesDeleteMutationData,
  Error,
  MessagesDeleteMutationVariables
> {
  const client = useKhulnasoftContext();
  return useMutation({
    ...buildMessagesDeleteMutation(client, options),
    ...options,
  });
}

export function mutationKeyMessagesDelete(): MutationKey {
  return ["@khulnasoft/api", "Messages", "delete"];
}

export function buildMessagesDeleteMutation(
  client$: KhulnasoftCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: MessagesDeleteMutationVariables,
  ) => Promise<MessagesDeleteMutationData>;
} {
  return {
    mutationKey: mutationKeyMessagesDelete(),
    mutationFn: function messagesDeleteMutationFn({
      messageId,
      idempotencyKey,
      options,
    }): Promise<MessagesDeleteMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(messagesDelete(
        client$,
        messageId,
        idempotencyKey,
        mergedOptions,
      ));
    },
  };
}
