# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import khulnasoft
import khulnasoft.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import nested as _nested
import khulnasoft_random

__all__ = ['FooArgs', 'Foo']

@khulnasoft.input_type
class FooArgs:
    def __init__(__self__):
        """
        The set of arguments for constructing a Foo resource.
        """
        pass


class Foo(khulnasoft.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[khulnasoft.ResourceOptions] = None,
                 __props__=None):
        """
        Create a Foo resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param khulnasoft.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[FooArgs] = None,
                 opts: Optional[khulnasoft.ResourceOptions] = None):
        """
        Create a Foo resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param FooArgs args: The arguments to use to populate this resource's properties.
        :param khulnasoft.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(FooArgs, khulnasoft.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[khulnasoft.ResourceOptions] = None,
                 __props__=None):
        opts = khulnasoft.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, khulnasoft.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = FooArgs.__new__(FooArgs)

        super(Foo, __self__).__init__(
            'example::Foo',
            resource_name,
            __props__,
            opts,
            remote=True)

    @khulnasoft.output_type
    class BarResult:
        def __init__(__self__, some_value=None):
            if some_value and not isinstance(some_value, str):
                raise TypeError("Expected argument 'some_value' to be a str")
            khulnasoft.set(__self__, "some_value", some_value)

        @property
        @khulnasoft.getter(name="someValue")
        def some_value(self) -> str:
            return khulnasoft.get(self, "some_value")

    def bar(__self__, *,
            baz_required: khulnasoft.Input['_nested.BazArgs'],
            bool_value_required: khulnasoft.Input[bool],
            name_required: khulnasoft.Input['khulnasoft_random.RandomPet'],
            string_value_required: khulnasoft.Input[str],
            baz: Optional[khulnasoft.Input['_nested.BazArgs']] = None,
            baz_plain: Optional['_nested.BazArgs'] = None,
            bool_value: Optional[khulnasoft.Input[bool]] = None,
            bool_value_plain: Optional[bool] = None,
            name: Optional[khulnasoft.Input['khulnasoft_random.RandomPet']] = None,
            name_plain: Optional['khulnasoft_random.RandomPet'] = None,
            string_value: Optional[khulnasoft.Input[str]] = None,
            string_value_plain: Optional[str] = None) -> khulnasoft.Output['Foo.BarResult']:
        """
        A description of bar.
        """
        __args__ = dict()
        __args__['__self__'] = __self__
        __args__['bazRequired'] = baz_required
        __args__['boolValueRequired'] = bool_value_required
        __args__['nameRequired'] = name_required
        __args__['stringValueRequired'] = string_value_required
        __args__['baz'] = baz
        __args__['bazPlain'] = baz_plain
        __args__['boolValue'] = bool_value
        __args__['boolValuePlain'] = bool_value_plain
        __args__['name'] = name
        __args__['namePlain'] = name_plain
        __args__['stringValue'] = string_value
        __args__['stringValuePlain'] = string_value_plain
        return khulnasoft.runtime.call('example::Foo/bar', __args__, res=__self__, typ=Foo.BarResult)

    def baz(__self__) -> None:
        __args__ = dict()
        __args__['__self__'] = __self__
        khulnasoft.runtime.call('example::Foo/baz', __args__, res=__self__)

    @khulnasoft.output_type
    class GenerateKubeconfigResult:
        def __init__(__self__, kubeconfig=None):
            if kubeconfig and not isinstance(kubeconfig, str):
                raise TypeError("Expected argument 'kubeconfig' to be a str")
            khulnasoft.set(__self__, "kubeconfig", kubeconfig)

        @property
        @khulnasoft.getter
        def kubeconfig(self) -> str:
            return khulnasoft.get(self, "kubeconfig")

    def generate_kubeconfig(__self__, *,
                            bool_value: bool) -> khulnasoft.Output['Foo.GenerateKubeconfigResult']:
        """
        Do something with something else
        """
        __args__ = dict()
        __args__['__self__'] = __self__
        __args__['boolValue'] = bool_value
        return khulnasoft.runtime.call('example::Foo/generateKubeconfig', __args__, res=__self__, typ=Foo.GenerateKubeconfigResult)

