# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import khulnasoft
import khulnasoft.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._enums import *

__all__ = [
    'Container',
]

@khulnasoft.output_type
class Container(dict):
    def __init__(__self__, *,
                 size: 'ContainerSize',
                 brightness: Optional['ContainerBrightness'] = None,
                 color: Optional[str] = None,
                 material: Optional[str] = None):
        khulnasoft.set(__self__, "size", size)
        if brightness is None:
            brightness = 1
        if brightness is not None:
            khulnasoft.set(__self__, "brightness", brightness)
        if color is not None:
            khulnasoft.set(__self__, "color", color)
        if material is not None:
            khulnasoft.set(__self__, "material", material)

    @property
    @khulnasoft.getter
    def size(self) -> 'ContainerSize':
        return khulnasoft.get(self, "size")

    @property
    @khulnasoft.getter
    def brightness(self) -> Optional['ContainerBrightness']:
        return khulnasoft.get(self, "brightness")

    @property
    @khulnasoft.getter
    def color(self) -> Optional[str]:
        return khulnasoft.get(self, "color")

    @property
    @khulnasoft.getter
    def material(self) -> Optional[str]:
        return khulnasoft.get(self, "material")


