# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import khulnasoft
import khulnasoft.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'TopLevel',
]

@khulnasoft.output_type
class TopLevel(dict):
    def __init__(__self__, *,
                 buzz: Optional[str] = None):
        if buzz is not None:
            khulnasoft.set(__self__, "buzz", buzz)

    @property
    @khulnasoft.getter
    def buzz(self) -> Optional[str]:
        return khulnasoft.get(self, "buzz")


