# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import khulnasoft_providerType.submod as __submod
    submod = __submod
else:
    submod = _utilities.lazy_import('khulnasoft_providerType.submod')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "providerType",
  "mod": "submod",
  "fqn": "khulnasoft_providerType.submod",
  "classes": {
   "providerType:submod:provider": "Provider"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "providerType",
  "token": "khulnasoft:providers:providerType",
  "fqn": "khulnasoft_providerType",
  "class": "Provider"
 }
]
"""
)
