# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .config import *
from .get_config import *
from .provider import *
from ._inputs import *
from . import outputs
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "cloudinit",
  "mod": "index/config",
  "fqn": "khulnasoft_cloudinit",
  "classes": {
   "cloudinit:index/config:Config": "Config"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "cloudinit",
  "token": "khulnasoft:providers:cloudinit",
  "fqn": "khulnasoft_cloudinit",
  "class": "Provider"
 }
]
"""
)
