// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package my8110

import (
	"context"
	"reflect"

	"github.com/khulnasoft/khulnasoft/sdk/v3/go/khulnasoft"
)

type MyEnum string

const (
	MyEnumOne = MyEnum("one")
	MyEnumTwo = MyEnum("two")
)

func (MyEnum) ElementType() reflect.Type {
	return reflect.TypeOf((*MyEnum)(nil)).Elem()
}

func (e MyEnum) ToMyEnumOutput() MyEnumOutput {
	return khulnasoft.ToOutput(e).(MyEnumOutput)
}

func (e MyEnum) ToMyEnumOutputWithContext(ctx context.Context) MyEnumOutput {
	return khulnasoft.ToOutputWithContext(ctx, e).(MyEnumOutput)
}

func (e MyEnum) ToMyEnumPtrOutput() MyEnumPtrOutput {
	return e.ToMyEnumPtrOutputWithContext(context.Background())
}

func (e MyEnum) ToMyEnumPtrOutputWithContext(ctx context.Context) MyEnumPtrOutput {
	return MyEnum(e).ToMyEnumOutputWithContext(ctx).ToMyEnumPtrOutputWithContext(ctx)
}

func (e MyEnum) ToStringOutput() khulnasoft.StringOutput {
	return khulnasoft.ToOutput(khulnasoft.String(e)).(khulnasoft.StringOutput)
}

func (e MyEnum) ToStringOutputWithContext(ctx context.Context) khulnasoft.StringOutput {
	return khulnasoft.ToOutputWithContext(ctx, khulnasoft.String(e)).(khulnasoft.StringOutput)
}

func (e MyEnum) ToStringPtrOutput() khulnasoft.StringPtrOutput {
	return khulnasoft.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e MyEnum) ToStringPtrOutputWithContext(ctx context.Context) khulnasoft.StringPtrOutput {
	return khulnasoft.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type MyEnumOutput struct{ *khulnasoft.OutputState }

func (MyEnumOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*MyEnum)(nil)).Elem()
}

func (o MyEnumOutput) ToMyEnumOutput() MyEnumOutput {
	return o
}

func (o MyEnumOutput) ToMyEnumOutputWithContext(ctx context.Context) MyEnumOutput {
	return o
}

func (o MyEnumOutput) ToMyEnumPtrOutput() MyEnumPtrOutput {
	return o.ToMyEnumPtrOutputWithContext(context.Background())
}

func (o MyEnumOutput) ToMyEnumPtrOutputWithContext(ctx context.Context) MyEnumPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v MyEnum) *MyEnum {
		return &v
	}).(MyEnumPtrOutput)
}

func (o MyEnumOutput) ToStringOutput() khulnasoft.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o MyEnumOutput) ToStringOutputWithContext(ctx context.Context) khulnasoft.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e MyEnum) string {
		return string(e)
	}).(khulnasoft.StringOutput)
}

func (o MyEnumOutput) ToStringPtrOutput() khulnasoft.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o MyEnumOutput) ToStringPtrOutputWithContext(ctx context.Context) khulnasoft.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e MyEnum) *string {
		v := string(e)
		return &v
	}).(khulnasoft.StringPtrOutput)
}

type MyEnumPtrOutput struct{ *khulnasoft.OutputState }

func (MyEnumPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**MyEnum)(nil)).Elem()
}

func (o MyEnumPtrOutput) ToMyEnumPtrOutput() MyEnumPtrOutput {
	return o
}

func (o MyEnumPtrOutput) ToMyEnumPtrOutputWithContext(ctx context.Context) MyEnumPtrOutput {
	return o
}

func (o MyEnumPtrOutput) Elem() MyEnumOutput {
	return o.ApplyT(func(v *MyEnum) MyEnum {
		if v != nil {
			return *v
		}
		var ret MyEnum
		return ret
	}).(MyEnumOutput)
}

func (o MyEnumPtrOutput) ToStringPtrOutput() khulnasoft.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o MyEnumPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) khulnasoft.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *MyEnum) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(khulnasoft.StringPtrOutput)
}

// MyEnumInput is an input type that accepts values of the MyEnum enum
// A concrete instance of `MyEnumInput` can be one of the following:
//
//	MyEnumOne
//	MyEnumTwo
type MyEnumInput interface {
	khulnasoft.Input

	ToMyEnumOutput() MyEnumOutput
	ToMyEnumOutputWithContext(context.Context) MyEnumOutput
}

var myEnumPtrType = reflect.TypeOf((**MyEnum)(nil)).Elem()

type MyEnumPtrInput interface {
	khulnasoft.Input

	ToMyEnumPtrOutput() MyEnumPtrOutput
	ToMyEnumPtrOutputWithContext(context.Context) MyEnumPtrOutput
}

type myEnumPtr string

func MyEnumPtr(v string) MyEnumPtrInput {
	return (*myEnumPtr)(&v)
}

func (*myEnumPtr) ElementType() reflect.Type {
	return myEnumPtrType
}

func (in *myEnumPtr) ToMyEnumPtrOutput() MyEnumPtrOutput {
	return khulnasoft.ToOutput(in).(MyEnumPtrOutput)
}

func (in *myEnumPtr) ToMyEnumPtrOutputWithContext(ctx context.Context) MyEnumPtrOutput {
	return khulnasoft.ToOutputWithContext(ctx, in).(MyEnumPtrOutput)
}

func init() {
	khulnasoft.RegisterInputType(reflect.TypeOf((*MyEnumInput)(nil)).Elem(), MyEnum("one"))
	khulnasoft.RegisterInputType(reflect.TypeOf((*MyEnumPtrInput)(nil)).Elem(), MyEnum("one"))
	khulnasoft.RegisterOutputType(MyEnumOutput{})
	khulnasoft.RegisterOutputType(MyEnumPtrOutput{})
}
