// Code generated by test DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mypkg

import (
	"github.com/khulnasoft/khulnasoft/sdk/v3/go/khulnasoft"
	"output-funcs-go-generics-only/mypkg/internal"
)

// Codegen demo with const inputs
func FuncWithConstInput(ctx *khulnasoft.Context, args *FuncWithConstInputArgs, opts ...khulnasoft.InvokeOption) error {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv struct{}
	err := ctx.Invoke("mypkg::funcWithConstInput", args, &rv, opts...)
	return err
}

type FuncWithConstInputArgs struct {
	PlainInput *string `khulnasoft:"plainInput"`
}
