[tool.poetry]
name = "khulnasoft"
version = "1.0.7a0"
description = "KhulnaSoft SDK that give agents cloud environments"
authors = ["khulnasoft <hello@khulnasoft.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://khulnasoft.com/"
repository = "https://github.com/khulnasoft/khulnasoft/tree/main/packages/python-sdk"
packages = [{ include = "khulnasoft" }, { include = "khulnasoft_connect" }]

[tool.poetry.dependencies]
python = "^3.8"

python-dateutil = ">=2.8.2"
protobuf = ">=3.20.0, <6.0.0"
httpcore = "^1.0.5"
httpx = ">=0.27.0, <1.0.0"
attrs = ">=23.2.0"
packaging = ">=24.1"
typing-extensions = ">=4.1.0"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
pytest = "^7.4.0"
pytest-xdist = "^3.3.1"
python-dotenv = "^1.0.0"
pytest-dotenv = "^0.5.2"
pytest-asyncio = "^0.23.7"
pydoc-markdown = "^4.8.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/khulnasoft/khulnasoft/issues"
