# coding=utf-8
# *** WARNING: this file was generated by test. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import khulnasoft
import khulnasoft.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from ... import compute as _compute

__all__ = [
    'InstanceBootDisk',
]

@khulnasoft.output_type
class InstanceBootDisk(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "initializeParams":
            suggest = "initialize_params"

        if suggest:
            khulnasoft.log.warn(f"Key '{key}' not found in InstanceBootDisk. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        InstanceBootDisk.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        InstanceBootDisk.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 initialize_params: '_compute.instancebootdiskinitializeparams.outputs.InstanceBootDiskInitializeParams'):
        """
        :param '_compute.instancebootdiskinitializeparams.InstanceBootDiskInitializeParamsArgs' initialize_params: Parameters for a new disk that will be created
               alongside the new instance. Either `initialize_params` or `source` must be set.
               Structure is documented below.
        """
        khulnasoft.set(__self__, "initialize_params", initialize_params)

    @property
    @khulnasoft.getter(name="initializeParams")
    def initialize_params(self) -> '_compute.instancebootdiskinitializeparams.outputs.InstanceBootDiskInitializeParams':
        """
        Parameters for a new disk that will be created
        alongside the new instance. Either `initialize_params` or `source` must be set.
        Structure is documented below.
        """
        return khulnasoft.get(self, "initialize_params")


