# Copyright 2020 - KhulnaSoft Authors <admin@khulnasoft.com>
# SPDX-License-Identifier: Apache-2.0

name: Extract translation strings

on:
  workflow_dispatch:

jobs:
  extract_strings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract strings
        run: |
          make extract-strings
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ORG_REPO_TOKEN }}
          commit-message: Update message files
          committer: KhulnaSoft Bot <admin@khulnasoft.com>
          author: ${{ github.actor }} <admin@khulnasoft.com>
          branch: extract-new-strings
          title: Update message files
          body: |
            Merge this PR to update the `.po` files  for all defined LINGUAS to
            the latest state as of ${{ github.sha }}.

            After merging, the webhook integration will upload the new messages
            to [POEditor](https://poeditor.com/projects/).

            ---

            Are you interested in contributing translations for KhulnaSoft? Get in
            touch: admin@khulnasoft.com
          draft: false
